---
- name: Samba auf vmLS4 einrichten
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Samba-Pakete installieren
      apt:
        name:
          - samba
          - samba-common-bin
          - smbclient
          - heimdal-clients
          - libpam-heimdal
          - libnss-winbind
          - libpam-winbind
        state: present
        update_cache: yes

    - name: Originale Samba-Konfiguration sichern
      copy:
        src: /etc/samba/smb.conf
        dest: /etc/samba/smb.conf.orig
        remote_src: yes

    - name: Leere smb.conf erstellen
      file:
        path: /etc/samba/smb.conf
        state: touch
        mode: 0644

    - name: Samba-Konfiguration hinzufügen
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [global]
          workgroup = SAMBADOM
          realm = SAMBADOM.SMARTLEARN.LAN
          security = ADS
          winbind enum users = yes
          winbind enum groups = yes
          winbind use default domain = yes
          winbind refresh tickets = yes
          template shell = /bin/bash
          idmap config * : range = 10000 - 19999
          idmap config SMARTLEARN : backend = rid
          idmap config SMARTLEARN : range = 1000000 - 1999999
          inherit acls = yes
          store dos attributes = yes
          client ipc signing = auto
          vfs objects = acl_xattr
          ldap server require strong auth = no

          [testshare]
          path = /home/vmadmin/testshare
          read only = no
          guest ok = no
          valid users = vmadmin

    - name: Samba neu starten
      systemd:
        name: smbd
        state: restarted

    - name: Konfiguration mit testparm überprüfen
      command: testparm
      register: testparm_result
      changed_when: false

    - name: Debug testparm output
      debug:
        var: testparm_result.stdout_lines
    
    - name: Kopiere smb.conf.orig in das Verzeichnis /home/vmadmin
      copy:
        src: /etc/samba/smb.conf.orig
        dest: /home/vmadmin/smb.conf.orig
        remote_src: yes
        owner: vmadmin
        group: vmadmin
        mode: 0644
