---
- name: Configure BIND9 DNS Server
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install BIND9, dnsutils, and openssl
      apt:
        name:
          - bind9
          - dnsutils
          - openssl
        state: present

    - name: Stop and disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    # rndc key tasks
    - name: Generate rndc key
      command: rndc-confgen -a -k ddns-key -c /etc/bind/ddns.key -r /dev/urandom
      args:
        creates: /etc/bind/ddns.key
      notify:
        - restart bind9

    - name: Create backup of named.conf
      copy:
        src: /etc/bind/named.conf
        dest: /etc/bind/named.conf.backup
        remote_src: yes

    - name: Create backup of named.conf.options
      copy:
        src: /etc/bind/named.conf.options
        dest: /etc/bind/named.conf.options.backup
        remote_src: yes

    - name: Create backup of named.conf.local
      copy:
        src: /etc/bind/named.conf.local
        dest: /etc/bind/named.conf.local.backup
        remote_src: yes

    - name: Create backup of named.conf.default-zones
      copy:
        src: /etc/bind/named.conf.default-zones
        dest: /etc/bind/named.conf.default-zones.backup
        remote_src: yes        

    - name: Create BIND zone template from db.empty
      command: cp /etc/bind/db.empty /etc/bind/db.template
      args:
        creates: /etc/bind/db.template

    - name: Update zone template with correct nameserver
      replace:
        path: /etc/bind/db.template
        regexp: 'localhost'
        replace: 'ns.devtech.swiss'
        backup: yes

    # Include ddns key into named.conf
    - name: Include DDNS key in named.conf
      lineinfile:
        path: /etc/bind/named.conf
        line: 'include "/etc/bind/ddns.key";'
        insertafter: EOF
        create: yes
        state: present

    - name: Configure named.conf.local with DDNS
      blockinfile:
        path: /etc/bind/named.conf.local
        create: yes
        block: |
          zone "devtech.swiss" {
              type master;
              file "/etc/bind/db.devtech.swiss";
              allow-update { key ddns-key; };
          };

          zone "234.27.172.in-addr.arpa" {
              type master;
              file "/etc/bind/db.172.27.234";
              allow-update { key ddns-key; };
          };

          zone "devtech.intern" {
              type master;
              file "/etc/bind/db.devtech.intern";
              allow-update { key ddns-key; };
          };

          zone "30.224.10.in-addr.arpa" {
              type master;
              file "/etc/bind/db.10.224.30";
              allow-update { key ddns-key; };
          };

    - name: Configure named.conf.options
      copy:
        dest: /etc/bind/named.conf.options
        content: |
          options {
              directory "/var/cache/bind";

              forwarders {
                  8.8.8.8;
              };

              allow-recursion {
                  172.27.234.128/27;
                  10.224.30.64/26;
              };

              dnssec-validation auto;

              listen-on-v6 { any; };
          };
        mode: 0644
      notify: restart bind9

    - name: Configure db.devtech.swiss
      copy:
        dest: /etc/bind/db.devtech.swiss
        content: |
          $TTL    85400
          @       IN      SOA     ns.devtech.swiss. root.devtech.swiss. (
                                        2              ; Serial
                                        604800         ; Refresh
                                        86400          ; Retry
                                        2419200        ; Expire
                                        86400 )        ; Negative Cache TTL
          ;
          @       IN      NS      ns.devtech.swiss.
          ns      IN      A       172.27.234.130
          srv-01  IN      A       172.27.234.130
          srv-02  IN      A       172.27.234.131
          www     IN      A       172.27.234.131
          ftp     IN      A       172.27.234.131
        mode: 0644
      notify: restart bind9

    - name: Configure db.172.27.234
      copy:
        dest: /etc/bind/db.172.27.234
        content: |
          $TTL    85400
          @       IN      SOA     ns.devtech.swiss. root.devtech.swiss. (
                                        2              ; Serial
                                        604800         ; Refresh
                                        86400          ; Retry
                                        2419200        ; Expire
                                        86400 )        ; Negative Cache TTL
          ;
          @       IN      NS      ns.devtech.swiss.
          130     IN      PTR     srv-01.devtech.swiss.
          131     IN      PTR     srv-02.devtech.swiss.
        mode: 0644
      notify: restart bind9

    - name: Configure db.devtech.intern
      copy:
        dest: /etc/bind/db.devtech.intern
        content: |
          $TTL    85400
          @       IN      SOA     ns.devtech.swiss. root.devtech.swiss. (
                                        2              ; Serial
                                        604800         ; Refresh
                                        86400          ; Retry
                                        2419200        ; Expire
                                        86400 )        ; Negative Cache TTL
          ;
          @       IN      NS      ns.devtech.swiss.
          ns      IN      A       172.27.234.130
          www     IN      A       172.27.234.131
          srv-03  IN      A       10.224.30.65
          srv-04  IN      A       10.224.30.66
        mode: 0644
      notify: restart bind9

    - name: Configure db.10.224.30
      copy:
        dest: /etc/bind/db.10.224.30
        content: |
          $TTL    85400
          @       IN      SOA     ns.devtech.swiss. root.devtech.swiss. (
                                        2              ; Serial
                                        604800         ; Refresh
                                        86400          ; Retry
                                        2419200        ; Expire
                                        86400 )        ; Negative Cache TTL
          ;
          @       IN      NS      ns.devtech.swiss.
          65      IN      PTR     srv-03.devtech.intern.
          66      IN      PTR     srv-04.devtech.intern.
        mode: 0644
      notify: restart bind9

    - name: Ensure BIND service is started and enabled
      service:
        name: named
        state: started
        enabled: yes

  handlers:
    - name: restart bind9
      service:
        name: named
        state: restarted
